version: '3.8'

services:
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres

  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2

  flyway:
    image: boxfuse/flyway:latest-alpine
    container_name: flyway-new
    command: -url=jdbc:postgresql://postgres:5432/employee -schemas=public -user=postgres -password=postgres migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    restart: on-failure
    depends_on:
      - postgres

volumes:
  postgres-data: